name: bikewatch
version: "1.0.0"
config-version: 2

profile: bikewatch
require-dbt-version: [">=1.10.5", "<2.0.0"]

model-paths: [models]
macro-paths: [macros]

# tells dbt where to find custom data tests
test-paths: [tests] 

clean-targets: [target, dbt_packages]

vars:
  allowed_clock_skew_seconds: 300
  station_stale_after_seconds: 2700

models:
  bikewatch:
    +persist_docs:
      relation: true
      columns: true

    example:
      +enabled: false

    staging:
      +materialized: view